import bra from './assets/bra.jpg'

export const Data = [
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 1,
        image: bra,
        price: 12.12,
        title: "Bra number 1",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 2,
        image: bra,
        price: 12.12,
        title: "Bra number 2",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 3,
        image: bra,
        price: 12.12,
        title: "Bra number 3",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 4,
        image: bra,
        price: 12.12,
        title: "Bra number 4",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 5,
        image: bra,
        price: 12.12,
        title: "Bra number 5",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 6,
        image: bra,
        price: 12.12,
        title: "Bra number 6",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 7,
        image: bra,
        price: 12.12,
        title: "Bra number 7",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 8,
        image: bra,
        price: 12.12,
        title: "Bra number 8",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 9,
        image: bra,
        price: 12.12,
        title: "Bra number 9",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 10,
        image: bra,
        price: 12.12,
        title: "Bra number 10",
    },
    {
        category: "bra",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 11,
        image: bra,
        price: 12.12,
        title: "Bra number 11",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 12,
        image: bra,
        price: 12.12,
        title: "Underwear number 1",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 13,
        image: bra,
        price: 12.12,
        title: "Underwear number 2",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 12,
        image: bra,
        price: 12.12,
        title: "Underwear number 1",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 13,
        image: bra,
        price: 12.12,
        title: "Underwear number 2",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 12,
        image: bra,
        price: 12.12,
        title: "Underwear number 1",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 13,
        image: bra,
        price: 12.12,
        title: "Underwear number 2",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 12,
        image: bra,
        price: 12.12,
        title: "Underwear number 1",
    },
    {
        category: "underwear",
        description: "This is where the description can go for the item. This is random text to showcase the page",
        id: 13,
        image: bra,
        price: 12.12,
        title: "Underwear number 2",
    }
]